# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
    ]
