# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20180817_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='belt_app.Quote'),
        ),
    ]
