# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20180817_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='uploader',
        ),
        migrations.AddField(
            model_name='quote',
            name='uploader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='q_user', to='belt_app.User'),
            preserve_default=False,
        ),
    ]
